name = "fb-marketing-dash-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "fb-marketing-dash-api"

[[env.production.routes]]
pattern = "api.odoo.pitcar.co.id/*"
zone_name = "pitcar.co.id" 